server {
    listen ${PORT};
    root /usr/share/nginx/html;
    index index.html;

    resolver 8.8.8.8 valid=30s;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        set $backend ${VITE_API_URL};
        proxy_pass $backend;
        proxy_set_header Host $proxy_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_ssl_server_name on;
    }
}
